config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :phone_number, :category, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian']}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

def new
  @restaurant = Restaurant.new
end

def show
  @restaurant = Restaurant.find(params[:id])
  @reviews = @restaurant.reviews
end

def create
  @restaurant = Restaurant.new(restaurant_params)
  @restaurant.save
end

def index
  @restaurants = Restaurant.all
end

# def edit
# end

# def update
# end

# def destroy
# end

private

def restaurant_params
  params.require(:restaurant).permit(:name, :address, :rating)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>the restaurant - INDEX</h1>
<% @restaurants.each do |restaurant|%>
<%= link_to restaurant.name, restaurant_path(restaurant)  %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%=@restaurant.name %></h1>
<% @reviews.each do |review|%>
<p>Rating: <%=link_to review.rating%></p>
<p>Comments: <%=review.content%></p>
<% end %>